/* GENERATED by tools/is1gl/protocol.py -- do not edit.
 * #included by hw/misc/is1gl.c. Regenerate with:
 *   python3 tools/is1gl/protocol.py tools/glshim/gl.h.guest \
 *       tools/glshim/glx.h.guest src/is1gl qemu/hw/misc
 * and commit both sides together - they are one protocol. */

static bool is1gl_replay_one(Is1glState *is1_, uint32_t opcode,
                             const uint8_t *rec_, uint32_t reclen_)
{
    (void)is1_;
    switch (opcode) {
    case IS1GL_OP_glClearColor: {
        if (reclen_ < 16) return false;
        float red = get_f32(rec_ + 0);
        float green = get_f32(rec_ + 4);
        float blue = get_f32(rec_ + 8);
        float alpha = get_f32(rec_ + 12);
        glClearColor(red, green, blue, alpha);
        return true;
    }
    case IS1GL_OP_glClear: {
        if (reclen_ < 4) return false;
        uint32_t mask = get_u32(rec_ + 0);
        glClear(mask);
        return true;
    }
    case IS1GL_OP_glBlendFunc: {
        if (reclen_ < 8) return false;
        uint32_t sfactor = get_u32(rec_ + 0);
        uint32_t dfactor = get_u32(rec_ + 4);
        glBlendFunc(sfactor, dfactor);
        return true;
    }
    case IS1GL_OP_glLineWidth: {
        if (reclen_ < 4) return false;
        float width = get_f32(rec_ + 0);
        glLineWidth(width);
        return true;
    }
    case IS1GL_OP_glScissor: {
        if (reclen_ < 16) return false;
        int32_t x = get_i32(rec_ + 0);
        int32_t y = get_i32(rec_ + 4);
        int32_t width = get_i32(rec_ + 8);
        int32_t height = get_i32(rec_ + 12);
        glScissor(x, y, width, height);
        return true;
    }
    case IS1GL_OP_glClipPlane: {
        if (reclen_ < 4) return false;
        uint32_t plane = get_u32(rec_ + 0);
        GLdouble equation[4];
        int i_;
        if (reclen_ < 4 + (uint32_t)(4) * 8) return false;
        for (i_ = 0; i_ < (int)(4); i_++)
            equation[i_] = get_f64(rec_ + 4 + i_ * 8);
        glClipPlane(plane, equation);
        return true;
    }
    case IS1GL_OP_glEnable: {
        if (reclen_ < 4) return false;
        uint32_t cap = get_u32(rec_ + 0);
        glEnable(cap);
        return true;
    }
    case IS1GL_OP_glDisable: {
        if (reclen_ < 4) return false;
        uint32_t cap = get_u32(rec_ + 0);
        glDisable(cap);
        return true;
    }
    case IS1GL_OP_glPushAttrib: {
        if (reclen_ < 4) return false;
        uint32_t mask = get_u32(rec_ + 0);
        glPushAttrib(mask);
        return true;
    }
    case IS1GL_OP_glPopAttrib: {
        glPopAttrib();
        return true;
    }
    case IS1GL_OP_glPushClientAttrib: {
        if (reclen_ < 4) return false;
        uint32_t mask = get_u32(rec_ + 0);
        glPushClientAttrib(mask);
        return true;
    }
    case IS1GL_OP_glPopClientAttrib: {
        glPopClientAttrib();
        return true;
    }
    case IS1GL_OP_glMatrixMode: {
        if (reclen_ < 4) return false;
        uint32_t mode = get_u32(rec_ + 0);
        glMatrixMode(mode);
        return true;
    }
    case IS1GL_OP_glViewport: {
        if (reclen_ < 16) return false;
        int32_t x = get_i32(rec_ + 0);
        int32_t y = get_i32(rec_ + 4);
        int32_t width = get_i32(rec_ + 8);
        int32_t height = get_i32(rec_ + 12);
        is1gl_host_glViewport(is1_, x, y, width, height);
        return true;
    }
    case IS1GL_OP_glPushMatrix: {
        glPushMatrix();
        return true;
    }
    case IS1GL_OP_glPopMatrix: {
        glPopMatrix();
        return true;
    }
    case IS1GL_OP_glLoadIdentity: {
        glLoadIdentity();
        return true;
    }
    case IS1GL_OP_glMultMatrixd: {
        GLdouble m[16];
        int i_;
        if (reclen_ < 0 + (uint32_t)(16) * 8) return false;
        for (i_ = 0; i_ < (int)(16); i_++)
            m[i_] = get_f64(rec_ + 0 + i_ * 8);
        glMultMatrixd(m);
        return true;
    }
    case IS1GL_OP_glMultMatrixf: {
        GLfloat m[16];
        int i_;
        if (reclen_ < 0 + (uint32_t)(16) * 4) return false;
        for (i_ = 0; i_ < (int)(16); i_++)
            m[i_] = get_f32(rec_ + 0 + i_ * 4);
        glMultMatrixf(m);
        return true;
    }
    case IS1GL_OP_glRotated: {
        if (reclen_ < 32) return false;
        double angle = get_f64(rec_ + 0);
        double x = get_f64(rec_ + 8);
        double y = get_f64(rec_ + 16);
        double z = get_f64(rec_ + 24);
        glRotated(angle, x, y, z);
        return true;
    }
    case IS1GL_OP_glRotatef: {
        if (reclen_ < 16) return false;
        float angle = get_f32(rec_ + 0);
        float x = get_f32(rec_ + 4);
        float y = get_f32(rec_ + 8);
        float z = get_f32(rec_ + 12);
        glRotatef(angle, x, y, z);
        return true;
    }
    case IS1GL_OP_glScalef: {
        if (reclen_ < 12) return false;
        float x = get_f32(rec_ + 0);
        float y = get_f32(rec_ + 4);
        float z = get_f32(rec_ + 8);
        glScalef(x, y, z);
        return true;
    }
    case IS1GL_OP_glTranslated: {
        if (reclen_ < 24) return false;
        double x = get_f64(rec_ + 0);
        double y = get_f64(rec_ + 8);
        double z = get_f64(rec_ + 16);
        glTranslated(x, y, z);
        return true;
    }
    case IS1GL_OP_glTranslatef: {
        if (reclen_ < 12) return false;
        float x = get_f32(rec_ + 0);
        float y = get_f32(rec_ + 4);
        float z = get_f32(rec_ + 8);
        glTranslatef(x, y, z);
        return true;
    }
    case IS1GL_OP_glDeleteLists: {
        if (reclen_ < 8) return false;
        uint32_t list = get_u32(rec_ + 0);
        int32_t range = get_i32(rec_ + 4);
        glDeleteLists(list, range);
        return true;
    }
    case IS1GL_OP_glNewList: {
        if (reclen_ < 8) return false;
        uint32_t list = get_u32(rec_ + 0);
        uint32_t mode = get_u32(rec_ + 4);
        glNewList(list, mode);
        return true;
    }
    case IS1GL_OP_glEndList: {
        glEndList();
        return true;
    }
    case IS1GL_OP_glCallList: {
        if (reclen_ < 4) return false;
        uint32_t list = get_u32(rec_ + 0);
        glCallList(list);
        return true;
    }
    case IS1GL_OP_glBegin: {
        if (reclen_ < 4) return false;
        uint32_t mode = get_u32(rec_ + 0);
        glBegin(mode);
        return true;
    }
    case IS1GL_OP_glEnd: {
        glEnd();
        return true;
    }
    case IS1GL_OP_glVertex2d: {
        if (reclen_ < 16) return false;
        double x = get_f64(rec_ + 0);
        double y = get_f64(rec_ + 8);
        glVertex2d(x, y);
        return true;
    }
    case IS1GL_OP_glVertex2f: {
        if (reclen_ < 8) return false;
        float x = get_f32(rec_ + 0);
        float y = get_f32(rec_ + 4);
        glVertex2f(x, y);
        return true;
    }
    case IS1GL_OP_glColor4f: {
        if (reclen_ < 16) return false;
        float red = get_f32(rec_ + 0);
        float green = get_f32(rec_ + 4);
        float blue = get_f32(rec_ + 8);
        float alpha = get_f32(rec_ + 12);
        glColor4f(red, green, blue, alpha);
        return true;
    }
    case IS1GL_OP_glTexCoord2f: {
        if (reclen_ < 8) return false;
        float s = get_f32(rec_ + 0);
        float t = get_f32(rec_ + 4);
        glTexCoord2f(s, t);
        return true;
    }
    case IS1GL_OP_glPixelStoref: {
        if (reclen_ < 8) return false;
        uint32_t pname = get_u32(rec_ + 0);
        float param = get_f32(rec_ + 4);
        glPixelStoref(pname, param);
        return true;
    }
    case IS1GL_OP_glPixelStorei: {
        if (reclen_ < 8) return false;
        uint32_t pname = get_u32(rec_ + 0);
        int32_t param = get_i32(rec_ + 4);
        glPixelStorei(pname, param);
        return true;
    }
    case IS1GL_OP_glDrawPixels: {
        if (reclen_ < 16) return false;
        int32_t width = get_i32(rec_ + 0);
        int32_t height = get_i32(rec_ + 4);
        uint32_t format = get_u32(rec_ + 8);
        uint32_t type = get_u32(rec_ + 12);
        const void *pixels = rec_ + 16;
        long need = is1gl_host_image_bytes(width, height, format, type);
        if (need < 0 || reclen_ < 16 + (uint32_t)need) return false;
        is1gl_host_glDrawPixels(width, height, format, type, pixels);
        return true;
    }
    case IS1GL_OP_glTexEnvf: {
        if (reclen_ < 12) return false;
        uint32_t target = get_u32(rec_ + 0);
        uint32_t pname = get_u32(rec_ + 4);
        float param = get_f32(rec_ + 8);
        glTexEnvf(target, pname, param);
        return true;
    }
    case IS1GL_OP_glTexEnvi: {
        if (reclen_ < 12) return false;
        uint32_t target = get_u32(rec_ + 0);
        uint32_t pname = get_u32(rec_ + 4);
        int32_t param = get_i32(rec_ + 8);
        glTexEnvi(target, pname, param);
        return true;
    }
    case IS1GL_OP_glTexParameterf: {
        if (reclen_ < 12) return false;
        uint32_t target = get_u32(rec_ + 0);
        uint32_t pname = get_u32(rec_ + 4);
        float param = get_f32(rec_ + 8);
        glTexParameterf(target, pname, param);
        return true;
    }
    case IS1GL_OP_glTexParameteri: {
        if (reclen_ < 12) return false;
        uint32_t target = get_u32(rec_ + 0);
        uint32_t pname = get_u32(rec_ + 4);
        int32_t param = get_i32(rec_ + 8);
        glTexParameteri(target, pname, param);
        return true;
    }
    case IS1GL_OP_glTexImage2D: {
        if (reclen_ < 32) return false;
        uint32_t target = get_u32(rec_ + 0);
        int32_t level = get_i32(rec_ + 4);
        int32_t internalFormat = get_i32(rec_ + 8);
        int32_t width = get_i32(rec_ + 12);
        int32_t height = get_i32(rec_ + 16);
        int32_t border = get_i32(rec_ + 20);
        uint32_t format = get_u32(rec_ + 24);
        uint32_t type = get_u32(rec_ + 28);
        const void *pixels = rec_ + 32;
        long need = is1gl_host_image_bytes(width, height, format, type);
        if (need < 0 || reclen_ < 32 + (uint32_t)need) return false;
        is1gl_host_glTexImage2D(target, level, internalFormat, width, height, border, format, type, pixels);
        return true;
    }
    case IS1GL_OP_glDeleteTextures: {
        if (reclen_ < 4) return false;
        int32_t n = get_i32(rec_ + 0);
        GLuint textures[64];
        int i_;
        if (n > 64 || n < 0) return false;
        if (reclen_ < 4 + (uint32_t)(n) * 4) return false;
        for (i_ = 0; i_ < (int)(n); i_++)
            textures[i_] = get_u32(rec_ + 4 + i_ * 4);
        glDeleteTextures(n, textures);
        return true;
    }
    case IS1GL_OP_glBindTexture: {
        if (reclen_ < 8) return false;
        uint32_t target = get_u32(rec_ + 0);
        uint32_t texture = get_u32(rec_ + 4);
        glBindTexture(target, texture);
        return true;
    }
    case IS1GL_OP_glTexSubImage2D: {
        if (reclen_ < 32) return false;
        uint32_t target = get_u32(rec_ + 0);
        int32_t level = get_i32(rec_ + 4);
        int32_t xoffset = get_i32(rec_ + 8);
        int32_t yoffset = get_i32(rec_ + 12);
        int32_t width = get_i32(rec_ + 16);
        int32_t height = get_i32(rec_ + 20);
        uint32_t format = get_u32(rec_ + 24);
        uint32_t type = get_u32(rec_ + 28);
        const void *pixels = rec_ + 32;
        long need = is1gl_host_image_bytes(width, height, format, type);
        if (need < 0 || reclen_ < 32 + (uint32_t)need) return false;
        is1gl_host_glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels);
        return true;
    }
    case IS1GL_OP_glCopyTexSubImage2D: {
        if (reclen_ < 32) return false;
        uint32_t target = get_u32(rec_ + 0);
        int32_t level = get_i32(rec_ + 4);
        int32_t xoffset = get_i32(rec_ + 8);
        int32_t yoffset = get_i32(rec_ + 12);
        int32_t x = get_i32(rec_ + 16);
        int32_t y = get_i32(rec_ + 20);
        int32_t width = get_i32(rec_ + 24);
        int32_t height = get_i32(rec_ + 28);
        glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
        return true;
    }
    default:
        return false;
    }
}
