/* GENERATED by tools/is1gl/protocol.py -- do not edit. */
#ifndef IS1GL_OPS_H
#define IS1GL_OPS_H

#define IS1GL_OP_NOP                      0
#define IS1GL_OP_WRAP                     1
#define IS1GL_OP_FENCE                    2
#define IS1GL_OP_MAKE_CURRENT             3
#define IS1GL_OP_SWAP                     4
#define IS1GL_OP_READPIXELS               5

#define IS1GL_OP_glClearColor             6
#define IS1GL_OP_glClear                  7
#define IS1GL_OP_glBlendFunc              8
#define IS1GL_OP_glLineWidth              9
#define IS1GL_OP_glScissor                10
#define IS1GL_OP_glClipPlane              11
#define IS1GL_OP_glEnable                 12
#define IS1GL_OP_glDisable                13
#define IS1GL_OP_glPushAttrib             14
#define IS1GL_OP_glPopAttrib              15
#define IS1GL_OP_glPushClientAttrib       16
#define IS1GL_OP_glPopClientAttrib        17
#define IS1GL_OP_glMatrixMode             18
#define IS1GL_OP_glViewport               19
#define IS1GL_OP_glPushMatrix             20
#define IS1GL_OP_glPopMatrix              21
#define IS1GL_OP_glLoadIdentity           22
#define IS1GL_OP_glMultMatrixd            23
#define IS1GL_OP_glMultMatrixf            24
#define IS1GL_OP_glRotated                25
#define IS1GL_OP_glRotatef                26
#define IS1GL_OP_glScalef                 27
#define IS1GL_OP_glTranslated             28
#define IS1GL_OP_glTranslatef             29
#define IS1GL_OP_glDeleteLists            30
#define IS1GL_OP_glNewList                31
#define IS1GL_OP_glEndList                32
#define IS1GL_OP_glCallList               33
#define IS1GL_OP_glBegin                  34
#define IS1GL_OP_glEnd                    35
#define IS1GL_OP_glVertex2d               36
#define IS1GL_OP_glVertex2f               37
#define IS1GL_OP_glColor4f                38
#define IS1GL_OP_glTexCoord2f             39
#define IS1GL_OP_glPixelStoref            40
#define IS1GL_OP_glPixelStorei            41
#define IS1GL_OP_glDrawPixels             42
#define IS1GL_OP_glTexEnvf                43
#define IS1GL_OP_glTexEnvi                44
#define IS1GL_OP_glTexParameterf          45
#define IS1GL_OP_glTexParameteri          46
#define IS1GL_OP_glTexImage2D             47
#define IS1GL_OP_glDeleteTextures         48
#define IS1GL_OP_glBindTexture            49
#define IS1GL_OP_glTexSubImage2D          50
#define IS1GL_OP_glCopyTexSubImage2D      51
#define IS1GL_OP_QT_PNG_DECODE            52

#define IS1GL_OP_COUNT 53

#define IS1GL_OP_NAMES_0 "NOP", "WRAP", "FENCE", "MAKE_CURRENT", "SWAP", "READPIXELS", "glClearColor", "glClear"
#define IS1GL_OP_NAMES_1 "glBlendFunc", "glLineWidth", "glScissor", "glClipPlane", "glEnable", "glDisable", "glPushAttrib", "glPopAttrib"
#define IS1GL_OP_NAMES_2 "glPushClientAttrib", "glPopClientAttrib", "glMatrixMode", "glViewport", "glPushMatrix", "glPopMatrix", "glLoadIdentity", "glMultMatrixd"
#define IS1GL_OP_NAMES_3 "glMultMatrixf", "glRotated", "glRotatef", "glScalef", "glTranslated", "glTranslatef", "glDeleteLists", "glNewList"
#define IS1GL_OP_NAMES_4 "glEndList", "glCallList", "glBegin", "glEnd", "glVertex2d", "glVertex2f", "glColor4f", "glTexCoord2f"
#define IS1GL_OP_NAMES_5 "glPixelStoref", "glPixelStorei", "glDrawPixels", "glTexEnvf", "glTexEnvi", "glTexParameterf", "glTexParameteri", "glTexImage2D"
#define IS1GL_OP_NAMES_6 "glDeleteTextures", "glBindTexture", "glTexSubImage2D", "glCopyTexSubImage2D", "QT_PNG_DECODE"
#define IS1GL_OP_NAMES { IS1GL_OP_NAMES_0, IS1GL_OP_NAMES_1, IS1GL_OP_NAMES_2, IS1GL_OP_NAMES_3, IS1GL_OP_NAMES_4, IS1GL_OP_NAMES_5, IS1GL_OP_NAMES_6 }

#endif
